spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snip
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false